theme = "nord"
        
[editor]
line-number = "absolute"
rulers = [80, 120]
bufferline = "multiple"
cursorline = true
color-modes = true
mouse = true

[editor.statusline]
left = ["mode", "spinner"]

center = ["file-absolute-path"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
git-ignore = true
max-depth = 10
[editor.search]
smart-case = true

[editor.indent-guides]
render = true
character = "|"
skip-levels = 0

[editor.smart-tab]
enable = false

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.lsp]
enable = true
